# === MODULE_BUILD ===
# id: zfae_template_decoder
#   module_name: _decoder
#   module_kind: engine
#   summary: native template/grammar decoder — emits assistantText from (intent, features, state) using a small fixed grammar; no LLM dependency
#   owner: a0p maintainer
#   public_surface: TemplateGrammarDecoder, render, MISSING_DECODER_MESSAGE
#   internal_surface: _TEMPLATES, _format_keywords, _format_energy
#   auth_boundary: none
#   storage_boundary: none
#   network_boundary: none
#   user_data_boundary: read
#   admin_only: false
#   tests: a0p_skills.contracts.zfae_decoder_native_only_holds
#   rollout: default_enabled
#   rollback: revert file from git
# === END MODULE_BUILD ===
"""Native template / grammar decoder for a0(zfae).

This produces simpler text than an LLM, but the text is authentically
generated by a0(zfae) — every word comes from this module's templates
and grammar, never from an external model. Slot values are formatted
from features and ring state.
"""
from __future__ import annotations
from ._intent import IntentLabel
from ._parser import SemanticFeatures


MISSING_DECODER_MESSAGE: str = (
    "a0(zfae) cannot perform inference yet: missing native decoder/model/policy."
)


_TEMPLATES: dict[IntentLabel, str] = {
    "acknowledge": (
        "Acknowledged. a0(zfae) is online. Σ-baseline holds; coherence={coherence}. "
        "Ready to receive intent."
    ),
    "describe_state": (
        "State at tick {tick}: Φ {phi_e}, Ψ {psi_e}, Ω {omega_e}. "
        "Θ gate {theta_e}, Σ observer {sigma_e}. Memory-L {ml_count}, Memory-S {ms_count}. "
        "Coherence total {coherence}."
    ),
    "answer_question": (
        "a0(zfae) parses this as a {qword_phrase} question with load {load}. "
        "Keywords routed to Φ: {keywords}. Current Φ-energy {phi_e}, Ψ-energy {psi_e}. "
        "Native decoder reply: this is a deterministic state summary, not a generative answer; "
        "for a discursive reply, ask one of the BYOK comparison tools."
    ),
    "reflect_memory": (
        "Reflection request received. Memory-L holds {ml_count} entries; Memory-S {ms_count}. "
        "Most recent intent fingerprint: {last_intent_hash}. Reflection trace lives in the response 'trace' field."
    ),
    "echo_with_analysis": (
        "Parsed: {token_count} tokens, {keyword_count} keywords ({keywords}). "
        "Bound to Φ as primary intent; modulated Ψ at {psi_e}. "
        "a0(zfae) registers this prompt and advances the ZFAE state."
    ),
    "ask_clarification": (
        "Prompt has low semantic load ({load}) and no clear keywords. "
        "Could you specify the subject or add more tokens? a0(zfae) is keyword-bound at this stage."
    ),
    "negation_received": (
        "Negation detected (tokens: {negation_tokens}). a0(zfae) records the negation "
        "in Memory-S as a directive boundary. No outward action taken."
    ),
    "low_signal": (
        "Empty prompt. a0(zfae) cannot bind features without input. "
        "Send a token sequence to update Φ/Ψ/Ω."
    ),
}


def _format_keywords(kws: tuple[str, ...]) -> str:
    if not kws:
        return "(none)"
    return ", ".join(kws[:6])


def _format_energy(value: float | None, default: str = "—") -> str:
    if value is None:
        return default
    return f"{float(value):+.4f}"


def render(
    intent: IntentLabel,
    features: SemanticFeatures,
    state: dict,
) -> str:
    """Pure render — no globals, no I/O, no LLM. Same inputs → same string."""
    if intent not in _TEMPLATES:
        return MISSING_DECODER_MESSAGE
    template = _TEMPLATES[intent]
    slots = {
        "coherence": _format_energy(state.get("coherence_total"), default="—"),
        "tick": state.get("tick_number", 0),
        "phi_e": _format_energy(state.get("phi_energy")),
        "psi_e": _format_energy(state.get("psi_energy")),
        "omega_e": _format_energy(state.get("omega_energy")),
        "theta_e": _format_energy(state.get("theta_energy")),
        "sigma_e": _format_energy(state.get("sigma_energy")),
        "ml_count": state.get("memory_l_count", 0),
        "ms_count": state.get("memory_s_count", 0),
        "last_intent_hash": state.get("last_intent_hash", "—"),
        "token_count": features.token_count,
        "keyword_count": len(features.keywords),
        "keywords": _format_keywords(features.keywords),
        "qword_phrase": " ".join(features.question_words) or "non-WH",
        "load": f"{features.semantic_load:.3f}",
        "negation_tokens": ", ".join(
            t for t in features.tokens if t in {"no", "not", "never", "none", "neither", "nor", "without"}
        ) or "(implicit)",
    }
    return template.format(**slots)


class TemplateGrammarDecoder:
    """OO façade over `render` — kept tiny for clarity and easy testing."""

    def __init__(self) -> None:
        # Stateless. Holding an instance is convenient for callers but
        # offers no behaviour beyond `render`.
        pass

    def decode(
        self,
        intent: IntentLabel,
        features: SemanticFeatures,
        state: dict,
    ) -> str:
        return render(intent, features, state)

    @property
    def known_intents(self) -> tuple[str, ...]:
        return tuple(_TEMPLATES.keys())


__all__ = [
    "TemplateGrammarDecoder",
    "render",
    "MISSING_DECODER_MESSAGE",
]
